spring:
  datasource:
    url: jdbc:mysql://192.168.7.73:3306/demo?characterEncoding=utf8&useConfigs=maxPerformance&rewriteBatchedStatements=true&useSSL=false&serverTimezone=GMT%2B8
    username: test
    password: P@ssw0rd